services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: larapee-app
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www
    depends_on:
      - db
      - rabbitmq
    networks:
      - larapee-network

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: larapee-reverb
    command: php artisan reverb:start --host=0.0.0.0 --port=8080
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www
    depends_on:
      - app
      - rabbitmq
    networks:
      - larapee-network


  web:
    image: nginx:alpine
    container_name: larapee-web
    ports:
      - "8001:80"
    volumes:
      - .:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - app
      - rabbitmq
    networks:
      - larapee-network

  # Python Analytics
  analytics:
    build:
      context: ./analytics
    container_name: larapee-analytics
    ports:
      - "5000:5000"
    volumes:
      - ./analytics:/app
    depends_on:
      - db
      - rabbitmq
    networks:
      - larapee-network

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: larapee-queue-worker
    command: php artisan queue:work rabbitmq --queue=default --tries=3 --timeout=90
    volumes:
      - .:/var/www
    depends_on:
      - app
      - db
      - rabbitmq
    networks:
      - larapee-network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: larapee-db
    environment:
      MYSQL_DATABASE: larapee
      MYSQL_USER: larapee_user
      MYSQL_PASSWORD: larapee_pass
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # ðŸŽ¯ á€’á€«á€€ data á€€á€­á€¯ á€…á€€á€ºá€‘á€²á€™á€¾á€¬ á€¡á€žá€±á€žá€­á€™á€ºá€¸á€•á€±á€¸á€™á€¾á€¬á€•á€«
    networks:
      - larapee-network

  # Message Broker (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: larapee-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - larapee-network
volumes:
  db_data:

networks:
  larapee-network:
    driver: bridge
